### ISSUE TITLE
Phasta incompressible does not compile well on BGQ with leslib

### ISSUE THREAD

**Issue by mrasquin** [PHASTA/phasta#11]
In order to compile phasta incompressible on BGQ with leslib active, I had to comment out a new ifdef HAVE_LESLIB statement in phSolver/incompressible/filters.f #1509, as well as lines #1518->1521.
The error message with these lines active is "Label contains characters that are not permitted. Label is ignored" for line #1518  and "syntax is incorrect" for line #1519. 
The same ifdef statement is used in order locations of the code without any issue. 
Phasta incompressible compiles fine on Linux.
Issue with cmake preprocessor on BGQ?

**Comment by acbauer** [comment]
I have pushed a branch which fixes this issue. I've created a pull request for this #12

**Comment by mrasquin** [comment]
Thanks Andy for the fix!
