### ISSUE TITLE
where is libles.a?

### ISSUE THREAD

**Issue by Watchmojo** [PHASTA/phasta#9]
Hi,

Sorry for this silly question. 

To compile this code, libles.a is required. What is this library? Where to download it?

Thank you very much,
Frank

**Comment by matthb2** [comment]
libles.a is a proprietary library which we can't distribute, but you don't need it. The compressible solver can use it's own internal (open source) solver or PETSc. The incompressible solver can use svLS as an alternative to libles. Review svLS/license.txt, and if you can meet the requirements, you can pass -DPHASTA_USE_SVLS=ON to cmake.
